setwd('~/Documents/a-mmm-lab/a-ml/data')
cdata = read.csv('5-crack-surface-normal.csv', header=T)
cor(cdata$distance_to_grain_boundary, cdata$dadN3Dline)
cor(cdata$dadN3Dline, cdata$distance_to_grain_boundary)
lm.fit=lm(dadN3Dline~scaled_angle,data=cdata)
lm.fit
summary(lm.fit)
confint(lm.fit)
predict(lm.fit,data.frame(scaled_angle=(c(0,.5,1,1.5))),interval ="confidence")
plot(cdata$scaled_angle,cdata$dadN3Dline)
abline(lm.fit,lwd=3,col='red')
par(mfrow=c(2,2))
plot(lm.fit)
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))

par(mfrow=c(1,1))
lm.fit=lm(dadN3Dline~scaled_angle+distance_to_grain_boundary,data=cdata)
summary(lm.fit)
lm.fit=lm(dadN3Dline~.,data=cdata)
summary(lm.fit)
lm.fit=lm(dadN3Dline~.-raw_angle-nearest_grain_boundary_id-normal_z-normal_y-normal_x-nearest_grain_phi2-nearest_grain_Phi-nearest_grain_phi1-phi2-Phi-phi1-unit_vector_to_grain_boundary_z-unit_vector_to_grain_boundary_y-unit_vector_to_grain_boundary_x-magnitude_of_vector_to_grain_boundary-vector_to_grain_boundary_z-vector_to_grain_boundary_y-vector_to_grain_boundary_x-nearest_grain_boundary_z-nearest_grain_boundary_y-nearest_grain_boundary_x-grain_id-z-y-x-theta-crack_id,data=cdata)
summary(lm.fit)
plot(cdata$distance_to_grain_boundary, cdata$dadN3Dline)
plot(cdata$misorientation, cdata$dadN3Dline)
plot(cdata$scaled_angle, cdata$dadN3Dline)
install.packages('car')
library(car)
vif(lm.fit)
lm.fit1=update(lm.fit, ~.-scaled_angle)

summary(lm(dadN3Dline~distance_to_grain_boundary*scaled_angle, data=cdata))
lm.fit2=lm(dadN3Dline~scaled_angle+I(scaled_angle^2), data=cdata)
attach(cdata)
summary(lm.fit2)
lm.fit=lm(dadN3Dline~scaled_angle)
anova(lm.fit,lm.fit2)
lm.fit=lm(dadN3Dline~poly(scaled_angle, 13))
summary(lm.fit)
